### PR TITLE
fix CI pipeline

### PR DESCRIPTION
**Pull request by Uzlopak**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by airhorns** [comment]
Why is this necessary? Isn't that the same resolution node itself would pick?

**Comment by Uzlopak** [comment]
Well it fixes the issue. I am not really eager to figue out, why this fixes jest. LOL

**Review by Eomm — APPROVED** [review]
I think the issue lives here:

image

+ jest does not resolve correctly the file to load.

This code forces jest to always use the same file IMHO

Maybe related: https://github.com/jestjs/jest/issues/9430

**Comment by Uzlopak** [comment]
Thank you. Lets merge and get the pipeline green

**Pull request merged**
