### PR TITLE
Fixes Issue #595 - Add state prop to AuthenticateOptions interface

### PR DESCRIPTION
**Pull request by louisnk**
#### Checklist

- [x] run `npm run test` and -`npm run benchmark`-
- [] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by airhorns — APPROVED** [review]

**Comment by louisnk** [comment]
Thank you for the quick turn @airhorns !

How does this get turned into a new version of the npm package? :)

**Comment by mmahkamov** [comment]
@airhorns When are you planning to release the fix?

We were migrating from Express to Fastify and came across this issue, which is now a blocker for us. I'd really appreciate if the fix could be released soon.

**Comment by kamui** [comment]
We've also been using a fork of your master branch as we wait for a release.

**Comment by mcollina** [comment]
Shipped!

**Pull request merged**
