### PR TITLE
chore(npm): switch fastify-secure-session to a dev dep

### PR DESCRIPTION
**Pull request by mgcrea**
Following the discussion in #91, this PR switches `fastify-secure-session` to a dev dep.

Would be great to have a published release soon :)!

### CODE REVIEW

**Comment by airhorns** [comment]
I don't think we should actually move the dependency until fastify-passport actually supports other session implementations, and in that case, I think it should be an optional dependency or a peer dependency, not a dev dependency. To actually make the session manager pluggable, we need to update the docs and explain how to register the different managers yourself.

Until that pluggability is a thing, I don't think we can ship this as is, as it will not install `fastify-secure-session` for all the people that do want to use it.

**Comment by airhorns** [comment]
Oh whoops didn't see that other PR -- I think that'd be the right place to move this dependency! Thanks for the contribution!

**Comment by airhorns** [comment]
I totally lied -- I forgot that this library doesn't actually register `fastify-secure-session` for you, and that the end user has to do that on their own. 😳 

In that case, this totally makes sense, as we don't need to force it to be included, the end developer should include it themselves, and when we add the different session manager support that should just work without having to adjust the dependencies.

Sorry for the confusion!

**Comment by mgcrea** [comment]
I was actually writing a blob about how I think it made no sense to keep it that way, even without the custom pluggable stores...! Thanks for the merge.

**Comment by airhorns** [comment]
Released in `v0.4.0` :)

**Pull request merged**
