### PR TITLE
fix authorize typings

### PR DESCRIPTION
**Pull request by Uzlopak**
Fixes the authorize typings as they were lacking the return type in the function overloads.

extracted from #646 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
@mcollina 

Not necessary as this project is written in typescript. It is implicitly checked by authorize.test.ts.

**Comment by mcollina** [comment]
Then why was not it failing before?

**Comment by Uzlopak** [comment]
Because it was implicitly derived from the return value of the actual implementation. But the overloaded function would afaik have any as return type. So it was less strict. 

I added now tsd...

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
