### PR TITLE
#932 fix:  avoid multiple calls to regenerate

### PR DESCRIPTION
**Pull request by jcbain**
This PR addresses this issue https://github.com/fastify/help/issues/932 in which `request.session.regenerate` will be called twice if `this.clearSessionOnLogin` is set to true (the default). This results in polluting the sessionStore with extra sessions.

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by marco-ippolito — APPROVED** [review]
LGTM

**Comment by marco-ippolito** [comment]
it seems the failure in the CI is not inherent to changes https://github.com/fastify/fastify-passport/actions/runs/6148307676/job/16685861064?pr=972

**Comment by jcbain** [comment]
> it seems the failure in the CI is not inherent to changes https://github.com/fastify/fastify-passport/actions/runs/6148307676/job/16685861064?pr=972

is there anything on my end that I can do to clear this up since it doesn't appear to be related to changes I introduced?

**Comment by Uzlopak** [comment]
#973 should fix the ci cd pipeline

**Comment by Uzlopak** [comment]
@jcbain 

please merge main into your branch and the ci cd pipeline should run through

**Comment by jcbain** [comment]
Thanks, all! Do you all have an estimate of when you would tag a new release?

**Comment by Uzlopak** [comment]
@eomm

**Pull request merged**
