### PR TITLE
[WIP] Support custom SessionManager

### PR DESCRIPTION
**Pull request by mgcrea**
Following the discussion in #91, I had a quick look at how we could support custom session manager.

It's not finished yet as it requires a bit of refactoring (instantiate the session manager later).

I'll update along the way, feel free to comment if you don't like some of the code changes.

### CODE REVIEW

**Review by leny32 — APPROVED** [review]
Looks good. Would very good to have customization.

**Comment by airhorns** [comment]
I think we should wait to review this until @mgcrea has suggested it is ready for review! Still missing tests and probably some other goodies.

**Comment by jsumners** [comment]
> I think we should wait to review this until @mgcrea has suggested it is ready for review! Still missing tests and probably some other goodies.

I missed the `[WIP]` 🤦‍♂️

**Comment by gperdomor** [comment]
Any progress here?

**Comment by jspantheonlab** [comment]
hihi, i have a stupid question, are there possible that set the session store to be `null`,  because i'm using `Authorization` header to authenticate.

**Pull request closed without merging**
